name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: config
      run: mkdir build
    - name: changedir
      run: cd build
    - name: check
      run: dir
    - name: cmake
      run: cmake .
    - name: make
      run: make
